version: '3.8'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:14.1
    container_name: postgres
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
    volumes:
      - /data:/app/data
  server:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres